name: bootstrap-forms-v3
After:
  - 'framework/*'
  - 'cms/*'
---
FormField:
  extensions:
    - BootstrapFormField
TextField:
  extensions:
    - BootstrapTextField
OptionsetField:
  extensions:
    - BootstrapOptionsetField
FormAction:
  extensions:
    - BootstrapFormAction
TextareaField:
  extensions:
    - BootstrapTextField
CheckboxField:
  extensions:
    - BootstrapCheckboxField_Extension
FieldList:
  extensions:
    - BootstrapFieldList
---
only:
  moduleexists: userforms
---
UserDefinedForm_Controller:
  extensions:
    - BootstrapUserForm
